<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-0A11AR8K" name="testNG_Scripts.profileCreation_TestNG" tests="12" failures="2" timestamp="29 Mar 2018 17:04:11 GMT" time="118.630" errors="0">
  <testcase name="PCApp_TestCase_002_C03" time="5.100" classname="testNG_Scripts.profileCreation_TestNG"/>
  <testcase name="PCApp_TestCase_002_C10" time="11.008" classname="testNG_Scripts.profileCreation_TestNG"/>
  <testcase name="PCApp_TestCase_002_C09" time="9.181" classname="testNG_Scripts.profileCreation_TestNG"/>
  <testcase name="PCApp_TestCase_002_C14" time="9.284" classname="testNG_Scripts.profileCreation_TestNG"/>
  <testcase name="PCApp_TestCase_002_C04" time="25.208" classname="testNG_Scripts.profileCreation_TestNG">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertFalse(Assert.java:65)at org.testng.Assert.assertFalse(Assert.java:75)at testNG_Scripts.profileCreation_TestNG.PCApp_TestCase_002_C04(profileCreation_TestNG.java:88)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- PCApp_TestCase_002_C04 -->
  <testcase name="PCApp_TestCase_002_C01" time="7.363" classname="testNG_Scripts.profileCreation_TestNG"/>
  <testcase name="PCApp_TestCase_002_C12" time="9.905" classname="testNG_Scripts.profileCreation_TestNG"/>
  <testcase name="PCApp_TestCase_002_C05" time="8.412" classname="testNG_Scripts.profileCreation_TestNG">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertFalse(Assert.java:65)at org.testng.Assert.assertFalse(Assert.java:75)at testNG_Scripts.profileCreation_TestNG.PCApp_TestCase_002_C05(profileCreation_TestNG.java:107)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- PCApp_TestCase_002_C05 -->
  <testcase name="PCApp_TestCase_002_C08" time="9.159" classname="testNG_Scripts.profileCreation_TestNG"/>
  <testcase name="PCApp_TestCase_002_C13" time="8.034" classname="testNG_Scripts.profileCreation_TestNG"/>
  <testcase name="PCApp_TestCase_002_C02" time="7.798" classname="testNG_Scripts.profileCreation_TestNG"/>
  <testcase name="PCApp_TestCase_002_C06" time="8.178" classname="testNG_Scripts.profileCreation_TestNG"/>
</testsuite> <!-- testNG_Scripts.profileCreation_TestNG -->
